theme: jekyll-theme-slate 
title: This is the homepage of Wang Tianle. Welcome!
description: Live is better than love.
plugins: 
    - jemoji 
url: "https://xiaoleorange.github.io" 
markdown: kramdown
